### ISSUE TITLE
Show Played Time for Super Hexagon

### ISSUE THREAD

**Issue by CharlotteGore** [aviraccoon/super-hexagon-stats#1]
Currently you're only showing the leaderboard. Another useful stat might be the total time a user has spent playing Super Hexagon on Steam. A useful tool for verifying that people with very very high scores have actually put in the work :)

**Comment by aviraccoon** [comment]
I wanted to add it, but the `IPlayerService/GetOwnedGames` API doesn't return playtime only for 1 game (it should, but it's broken) - getting playtime for all games would be a waste of bandwidth and time. And even then I would need to fetch API over 115k times because it doesn't support multiple Steam IDs. :disappointed:

I'm closing this issue for now, but I'll try to bug Valve about this.

**Comment by aviraccoon** [comment]
Oops, I meant issue #2 in the commit :P

Well, web API is still broken, it looks like Valve will rather add more trading cards crap (there's now API for levels and badges) than fix bugs like this.

**Comment by aviraccoon** [comment]
Playtime for 1 game finally works. Still not going to fetch 400k+ users every day just to get a playtime (Valve would hate me), but I can probably load it and save when someone visits a profile.

Note for self: Request must be in this format:

```
http://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=STEAM_API_KEY&format=json&input_json={%22steamid%22:76561198020275445,%22appids_filter%22:[221640]}
```

**Comment by CharlotteGore** [comment]
Awesome :)

**Comment by aviraccoon** [comment]
Closing as I'm archiving this repository.
